#!/usr/bin/env python3
"""
多格式生成器 - 同时生成 HTML + Markdown
"""
import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


def generate_markdown(news_data, date_str):
    """生成 Markdown"""
    lines = [
        f"# 科技新闻快报 | {date_str}",
        "",
        f"> 本期精选 **{news_data.get('total_filtered', 0)}** 条科技新闻",
        "",
        "---",
        "",
    ]

    for i, item in enumerate(news_data.get("items", []), 1):
        title = item.get("title", "")
        content = item.get("description", "") or item.get("content", "")
        source = item.get("source", "")
        link = item.get("link", "")
        relevance = item.get("relevance_score", 0)
        entities = item.get("entities", [])

        lines.extend([
            f"## {i}. {title}",
            "",
            f"**来源**: {source} | **相关度**: {relevance}",
            "",
            f"{content[:300]}..." if len(content) > 300 else content,
            "",
            f"[阅读原文]({link})",
            "",
        ])

        if entities:
            lines.append(f"**标签**: {', '.join(entities)}")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.extend([
        "",
        "*Generated by Daily Tech News Digest*",
    ])

    return "\n".join(lines)


def generate_html(news_data, date_str):
    """生成极简 HTML"""
    items_html = []

    for item in news_data.get("items", []):
        content = item.get("description", "") or item.get("content", "")
        import re
        content = re.sub(r"<[^>]+>", "", content)
        if len(content) > 250:
            content = content[:250] + "..."

        entities = item.get("entities", [])
        tags_html = "".join([f'<span class="tag">{e}</span>' for e in entities[:3]])

        item_html = f'''
<article class="news-item">
    <h2>{item.get("title", "")}</h2>
    <div class="meta">
        <span>{item.get("source", "")}</span>
        <span>相关度: {item.get("relevance_score", 0)}</span>
    </div>
    <div class="content">{content}</div>
    <div class="link"><a href="{item.get("link", "#")}" target="_blank">阅读原文 →</a></div>
    <div class="tags">{tags_html}</div>
</article>
'''
        items_html.append(item_html)

    return f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>科技新闻快报 | {date_str}</title>
    <style>
        *{{margin:0;padding:0;box-sizing:border-box}}
        body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;line-height:1.6;color:#333;max-width:720px;margin:0 auto;padding:60px 20px}}
        header{{margin-bottom:60px;padding-bottom:30px;border-bottom:1px solid #eee}}
        h1{{font-size:28px;font-weight:400;margin-bottom:8px}}
        .date{{font-size:14px;color:#999}}
        .summary{{font-size:15px;color:#666;margin-bottom:50px;padding:20px 0;border-bottom:1px solid #f5f5f5}}
        .news-item{{margin-bottom:50px;padding-bottom:40px;border-bottom:1px solid #f5f5f5}}
        .news-item:last-child{{border-bottom:none}}
        .news-item h2{{font-size:18px;font-weight:500;line-height:1.5;margin-bottom:12px;color:#111}}
        .meta{{font-size:12px;color:#999;margin-bottom:15px}}
        .meta span{{margin-right:15px}}
        .content{{font-size:15px;line-height:1.8;color:#444;margin-bottom:15px}}
        .link a{{color:#0066cc;text-decoration:none;font-size:13px}}
        .tags{{margin-top:15px}}
        .tag{{display:inline-block;font-size:11px;color:#666;background:#f5f5f5;padding:3px 10px;margin-right:6px;border-radius:2px}}
        footer{{margin-top:80px;padding-top:30px;border-top:1px solid #eee;font-size:12px;color:#999;text-align:center}}
    </style>
</head>
<body>
    <header><h1>科技新闻快报</h1><div class="date">{date_str}</div></header>
    <div class="summary">本期精选 <strong>{news_data.get('total_filtered', 0)}</strong> 条科技新闻</div>
    <main>{"".join(items_html)}</main>
    <footer>Generated by Daily Tech News Digest</footer>
</body>
</html>
'''


def main():
    parser = argparse.ArgumentParser(description="生成多格式新闻")
    parser.add_argument("--input", required=True, help="输入JSON")
    parser.add_argument("--output-dir", required=True, help="输出目录")
    parser.add_argument("--date", help="日期")
    parser.add_argument("--summary", action="store_true", help="生成AI总结")
    args = parser.parse_args()

    print("=" * 50)
    print("多格式生成器 (HTML + Markdown + RSS)")
    print("=" * 50)

    # 读取数据
    with open(args.input, "r", encoding="utf-8") as f:
        news_data = json.load(f)

    date_str = args.date or news_data.get("date", datetime.now().strftime("%Y-%m-%d"))
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 生成 HTML
    print(f"\n[1/4] 生成 HTML...")
    html = generate_html(news_data, date_str)
    html_path = output_dir / "index.html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  ✓ {html_path}")

    # 生成 Markdown
    print(f"\n[2/4] 生成 Markdown...")
    md = generate_markdown(news_data, date_str)
    md_path = output_dir / "index.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"  ✓ {md_path}")

    # 生成 RSS
    print(f"\n[3/4] 生成 RSS...")
    import subprocess
    rss_result = subprocess.run(
        ["python", "scripts/generate-rss.py", "--input", args.input, "--output", str(output_dir / "rss.xml")],
        capture_output=True, text=True
    )
    if rss_result.returncode == 0:
        print(f"  ✓ {output_dir / 'rss.xml'}")
    else:
        print(f"  ⚠ RSS 生成失败")

    # 生成 AI 总结
    if args.summary:
        print(f"\n[4/4] 生成 AI 总结...")
        summary_result = subprocess.run(
            ["python", "scripts/generate-summary.py", "--input", args.input, "--output", str(output_dir / "summary.md"), "--llm", "simple"],
            capture_output=True, text=True
        )
        if summary_result.returncode == 0:
            print(f"  ✓ {output_dir / 'summary.md'}")
        else:
            print(f"  ⚠ 总结生成失败")

    print(f"\n✓ 全部生成完成")
    print(f"  输出目录: {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
