#!/usr/bin/env python3
"""
生成极简主义风格的静态 HTML 新闻页面
"""
import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>科技新闻快报 | {{date}}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #fff;
            max-width: 720px;
            margin: 0 auto;
            padding: 60px 20px;
        }

        header {
            margin-bottom: 60px;
            padding-bottom: 30px;
            border-bottom: 1px solid #eee;
        }

        h1 {
            font-size: 28px;
            font-weight: 400;
            letter-spacing: -0.5px;
            margin-bottom: 8px;
        }

        .date {
            font-size: 14px;
            color: #999;
        }

        .summary {
            font-size: 15px;
            color: #666;
            margin-bottom: 50px;
            padding: 20px 0;
            border-bottom: 1px solid #f5f5f5;
        }

        .news-item {
            margin-bottom: 50px;
            padding-bottom: 40px;
            border-bottom: 1px solid #f5f5f5;
        }

        .news-item:last-child {
            border-bottom: none;
        }

        .news-item h2 {
            font-size: 18px;
            font-weight: 500;
            line-height: 1.5;
            margin-bottom: 12px;
            color: #111;
        }

        .meta {
            font-size: 12px;
            color: #999;
            margin-bottom: 15px;
        }

        .meta span {
            margin-right: 15px;
        }

        .content {
            font-size: 15px;
            line-height: 1.8;
            color: #444;
            margin-bottom: 15px;
        }

        .link {
            font-size: 13px;
        }

        .link a {
            color: #0066cc;
            text-decoration: none;
            border-bottom: 1px solid transparent;
            transition: border-color 0.2s;
        }

        .link a:hover {
            border-bottom-color: #0066cc;
        }

        .tags {
            margin-top: 15px;
        }

        .tag {
            display: inline-block;
            font-size: 11px;
            color: #666;
            background: #f5f5f5;
            padding: 3px 10px;
            margin-right: 6px;
            border-radius: 2px;
        }

        footer {
            margin-top: 80px;
            padding-top: 30px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #999;
            text-align: center;
        }

        @media print {
            body {
                padding: 40px 20px;
            }
            .link a {
                text-decoration: underline;
            }
        }
    </style>
</head>
<body>
    <header>
        <h1>科技新闻快报</h1>
        <div class="date">{{date}}</div>
    </header>

    <div class="summary">
        本期精选 <strong>{{total}}</strong> 条科技新闻
    </div>

    <main>
        {{news_items}}
    </main>

    <footer>
        Generated by Daily Tech News Digest
    </footer>
</body>
</html>
'''

NEWS_ITEM_TEMPLATE = '''
<article class="news-item">
    <h2>{{title}}</h2>
    <div class="meta">
        <span>{{source}}</span>
        <span>相关度: {{relevance}}</span>
    </div>
    <div class="content">
        {{content}}
    </div>
    <div class="link">
        <a href="{{link}}" target="_blank" rel="noopener">阅读原文 →</a>
    </div>
    {{tags}}
</article>
'''


def generate_html(news_data, date_str):
    """生成HTML内容"""
    items_html = []

    for item in news_data.get("items", []):
        # 截断内容
        content = item.get("description", "") or item.get("content", "")
        import re
        content = re.sub(r"<[^>]+>", "", content)
        if len(content) > 250:
            content = content[:250] + "..."

        # 生成标签
        entities = item.get("entities", [])
        tags_html = ""
        if entities:
            tags_html = '<div class="tags">' + "".join([f'<span class="tag">{e}</span>' for e in entities[:3]]) + "</div>"

        item_html = (NEWS_ITEM_TEMPLATE
            .replace("{{title}}", item.get("title", ""))
            .replace("{{source}}", item.get("source", ""))
            .replace("{{relevance}}", str(item.get("relevance_score", 0)))
            .replace("{{content}}", content)
            .replace("{{link}}", item.get("link", "#"))
            .replace("{{tags}}", tags_html))

        items_html.append(item_html)

    return (HTML_TEMPLATE
        .replace("{{date}}", date_str)
        .replace("{{total}}", str(news_data.get("total_filtered", 0)))
        .replace("{{news_items}}", "".join(items_html)))


def main():
    parser = argparse.ArgumentParser(description="生成极简HTML新闻页面")
    parser.add_argument("--input", required=True, help="输入JSON文件路径")
    parser.add_argument("--output", required=True, help="输出HTML文件路径")
    parser.add_argument("--date", help="日期 (YYYY-MM-DD)")
    args = parser.parse_args()

    print("=" * 50)
    print("HTML 生成器 (极简主义风格)")
    print("=" * 50)

    # 读取数据
    print(f"\n读取: {args.input}")
    with open(args.input, "r", encoding="utf-8") as f:
        news_data = json.load(f)
    print(f"  ✓ {news_data.get('total_filtered', 0)} 条新闻")

    # 生成HTML
    date_str = args.date or news_data.get("date", datetime.now().strftime("%Y-%m-%d"))
    html_content = generate_html(news_data, date_str)

    # 保存
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    file_size = output_path.stat().st_size / 1024
    print(f"\n✓ 生成成功: {output_path}")
    print(f"✓ 文件大小: {file_size:.1f} KB")
    print(f"✓ 可直接在浏览器中打开")

    return 0


if __name__ == "__main__":
    sys.exit(main())
