#!/usr/bin/env python3
"""
PDF生成脚本 - 使用FPDF2生成嵌入字体的中文PDF
"""
import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from fpdf import FPDF


class ChinesePDF(FPDF):
    """支持中文的PDF类"""

    def __init__(self, font_path):
        super().__init__()
        self.font_path = font_path
        self.add_font("NotoSansCJK", "", font_path, uni=True)
        self.add_font("NotoSansCJK", "B", font_path, uni=True)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        """页眉"""
        self.set_font("NotoSansCJK", "", 10)
        self.set_text_color(102, 102, 102)
        self.cell(0, 10, f"科技新闻快报 - {datetime.now().strftime('%Y-%m-%d')}", align="C", ln=True)
        self.ln(5)

    def footer(self):
        """页脚"""
        self.set_y(-15)
        self.set_font("NotoSansCJK", "", 10)
        self.set_text_color(102, 102, 102)
        self.cell(0, 10, f"第 {self.page_no()} 页", align="C")


def create_pdf(news_data, output_path, font_path):
    """创建PDF文档"""
    pdf = ChinesePDF(font_path)
    pdf.add_page()

    # 标题
    pdf.set_font("NotoSansCJK", "B", 24)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 15, "科技新闻快报", align="C", ln=True)

    # 日期
    pdf.set_font("NotoSansCJK", "", 12)
    pdf.set_text_color(102, 102, 102)
    date_str = news_data.get("date", datetime.now().strftime("%Y-%m-%d"))
    pdf.cell(0, 10, date_str, align="C", ln=True)
    pdf.ln(10)

    # 分隔线
    pdf.set_draw_color(0, 102, 204)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)

    # 摘要
    total = news_data.get("total_filtered", 0)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("NotoSansCJK", "", 10)
    pdf.set_text_color(102, 102, 102)
    pdf.multi_cell(0, 8, f"本期精选 {total} 条科技新闻，涵盖 AI、互联网、硬件等领域。", fill=True)
    pdf.ln(10)

    # 新闻列表
    for i, item in enumerate(news_data.get("items", []), 1):
        # 新闻标题
        pdf.set_font("NotoSansCJK", "B", 14)
        pdf.set_text_color(51, 51, 51)
        title = item.get("title", "")
        pdf.multi_cell(0, 8, title)
        pdf.ln(2)

        # 元信息
        pdf.set_font("NotoSansCJK", "", 9)
        pdf.set_text_color(136, 136, 136)
        source = item.get("source", "")
        relevance = item.get("relevance_score", 0)
        entities = ", ".join(item.get("entities", []))
        meta_text = f"来源: {source} | 相关度: {relevance}"
        if entities:
            meta_text += f" | 标签: {entities}"
        pdf.cell(0, 6, meta_text, ln=True)
        pdf.ln(2)

        # 正文
        pdf.set_font("NotoSansCJK", "", 11)
        pdf.set_text_color(85, 85, 85)
        content = item.get("description", "") or item.get("content", "")
        # 清理HTML标签
        import re
        content = re.sub(r"<[^>]+>", "", content)
        if len(content) > 300:
            content = content[:300] + "..."
        pdf.multi_cell(0, 6, content)
        pdf.ln(2)

        # 链接
        pdf.set_font("NotoSansCJK", "", 8)
        pdf.set_text_color(0, 102, 204)
        link = item.get("link", "")
        pdf.cell(0, 5, f"原文链接: {link}", ln=True)
        pdf.ln(2)

        # 分隔线
        pdf.set_draw_color(238, 238, 238)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(8)

    # 页脚信息
    pdf.ln(10)
    pdf.set_font("NotoSansCJK", "", 8)
    pdf.set_text_color(153, 153, 153)
    pdf.cell(0, 5, f"Generated by Daily Tech News Digest - {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")

    # 保存PDF
    pdf.output(output_path)
    return True


def main():
    parser = argparse.ArgumentParser(description="生成中文新闻PDF (FPDF2)")
    parser.add_argument("--input", required=True, help="输入JSON文件路径")
    parser.add_argument("--output", required=True, help="输出PDF文件路径")
    parser.add_argument("--date", help="日期 (YYYY-MM-DD)")
    args = parser.parse_args()

    print("=" * 50)
    print("PDF生成器 (FPDF2 + 字体嵌入)")
    print("=" * 50)

    # 查找字体文件
    font_paths = [
        Path(__file__).parent.parent / "fonts" / "NotoSansCJKsc-Regular.otf",
        Path(__file__).parent.parent / "fonts" / "NotoSansCJKsc-Bold.otf",
    ]

    font_path = None
    for fp in font_paths:
        if fp.exists():
            font_path = str(fp)
            print(f"\n[1/3] 找到字体: {fp.name}")
            break

    if not font_path:
        print("\n[1/3] ✗ 错误: 未找到中文字体文件")
        print("请确保 fonts/ 目录下有 NotoSansCJKsc-Regular.otf")
        return 1

    # 读取新闻数据
    print(f"\n[2/3] 读取新闻数据: {args.input}")
    try:
        with open(args.input, "r", encoding="utf-8") as f:
            news_data = json.load(f)
        print(f"  ✓ 读取 {news_data.get('total_filtered', 0)} 条新闻")
    except Exception as e:
        print(f"  ✗ 读取失败: {e}")
        return 1

    # 生成PDF
    print("\n[3/3] 生成PDF...")
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        create_pdf(news_data, str(output_path), font_path)
        file_size = output_path.stat().st_size / 1024  # KB
        print(f"  ✓ PDF生成成功: {output_path}")
        print(f"  ✓ 文件大小: {file_size:.1f} KB")
        print(f"  ✓ 字体已嵌入")
        return 0
    except Exception as e:
        print(f"  ✗ PDF生成失败: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
