#!/usr/bin/env python3
"""
多格式生成器 - 同时生成 HTML + Markdown + RSS
"""
import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def generate_markdown(news_data, date_str):
    """生成 Markdown"""
    lines = [
        f"# 科技新闻快报 | {date_str}",
        "",
        f"> 本期精选 **{news_data.get('total_filtered', 0)}** 条科技新闻",
        "",
        "---",
        "",
    ]

    for i, item in enumerate(news_data.get("items", []), 1):
        title = item.get("title", "")
        content = item.get("description", "") or item.get("content", "")
        source = item.get("source", "")
        link = item.get("link", "")
        relevance = item.get("relevance_score", 0)
        entities = item.get("entities", [])

        lines.extend([
            f"## {i}. {title}",
            "",
            f"**来源**: {source} | **相关度**: {relevance}",
            "",
            f"{content[:300]}..." if len(content) > 300 else content,
            "",
            f"[阅读原文]({link})",
            "",
        ])

        if entities:
            lines.append(f"**标签**: {', '.join(entities)}")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.extend([
        "",
        "*Generated by Daily Tech News Digest*",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="生成多格式新闻")
    parser.add_argument("--input", required=True, help="输入JSON")
    parser.add_argument("--output-dir", required=True, help="输出目录")
    parser.add_argument("--date", help="日期")
    parser.add_argument("--summary", action="store_true", help="生成AI总结")
    args = parser.parse_args()

    print("=" * 50)
    print("多格式生成器 (HTML + Markdown + RSS)")
    print("=" * 50)

    # 读取数据
    with open(args.input, "r", encoding="utf-8") as f:
        news_data = json.load(f)

    date_str = args.date or news_data.get("date", datetime.now().strftime("%Y-%m-%d"))
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 生成 HTML (调用 generate-html.py)
    print(f"\n[1/4] 生成 HTML...")
    html_path = output_dir / "index.html"
    html_result = subprocess.run(
        ["python", "scripts/generate-html.py", "--input", args.input, "--output", str(html_path), "--date", date_str],
        capture_output=True, text=True
    )
    if html_result.returncode == 0:
        print(f"  ✓ {html_path}")
    else:
        print(f"  ⚠ HTML 生成失败: {html_result.stderr}")

    # 生成 Markdown
    print(f"\n[2/4] 生成 Markdown...")
    md = generate_markdown(news_data, date_str)
    md_path = output_dir / "index.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"  ✓ {md_path}")

    # 生成 RSS
    print(f"\n[3/4] 生成 RSS...")
    rss_result = subprocess.run(
        ["python", "scripts/generate-rss.py", "--input", args.input, "--output", str(output_dir / "rss.xml")],
        capture_output=True, text=True
    )
    if rss_result.returncode == 0:
        print(f"  ✓ {output_dir / 'rss.xml'}")
    else:
        print(f"  ⚠ RSS 生成失败")

    # 生成 AI 总结
    if args.summary:
        print(f"\n[4/4] 生成 AI 总结...")
        summary_result = subprocess.run(
            ["python", "scripts/generate-summary.py", "--input", args.input, "--output", str(output_dir / "summary.md"), "--llm", "simple"],
            capture_output=True, text=True
        )
        if summary_result.returncode == 0:
            print(f"  ✓ {output_dir / 'summary.md'}")
        else:
            print(f"  ⚠ 总结生成失败")

    print(f"\n✓ 全部生成完成")
    print(f"  输出目录: {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
